// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAhB5WTeS3jLW4Jh1MDE3Z8AGGM4KgsDtw",
      authDomain: "tiktokclone-da8f4.firebaseapp.com",
      projectId: "tiktokclone-da8f4",
      storageBucket: "tiktokclone-da8f4.appspot.com",
      messagingSenderId: "1044314579932",
      appId: "1:1044314579932:web:311c754f69b4d464d4e519"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMjCDlCBzXuDOGk-rOn2Tvr7AGekcfNks',
    appId: '1:1044314579932:android:19b35d67f1be057cd4e519',
    messagingSenderId: '1044314579932',
    projectId: 'tiktokclone-da8f4',
    storageBucket: 'tiktokclone-da8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN5Rgc9Is9zqkuer0rXkshcMZLxa0l1JQ',
    appId: '1:1044314579932:ios:fa680bb06e6482bcd4e519',
    messagingSenderId: '1044314579932',
    projectId: 'tiktokclone-da8f4',
    storageBucket: 'tiktokclone-da8f4.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

}